let name = "Zsu"
console.log(name+"'s apples")
$("h1").text("We are having a break")
$("p").html("StayAtHome Coding Camp Likes: <strong>13</strong>")
$("strong").css("background", "lime")
$("strong").css("padding", "5px")
$("h2").toggleClass("blue")
$("h2").toggleClass("blue")
$("ul").append("<li id="special-list-item" >My name is " + name + "</li>")
$("#special-list-item").remove()
